language: java
jdk: openjdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/501b2442e1478419c3a5
    on_success: change
    on_failure: always
    on_start: never
after_success:
  - "bash ./.travis-deploy.sh"
env:
  global:
    - secure: "i5VXsJl3ALerKqQy933tEZI2FnDsLl3D+StVVmw6SQlKiH8TocEXXFBHxlpOr+VOJ3Uiubju5eprmEE3l5T1Z0eKIT9E2Q/0F+7b4E8vWfjstbQr8V1cwm/FmgUSCKnMHdEFtKRPB37OtDzkYDrpiDuW5fn+hkr8myNEhjOVngXUNR671l4KHmpWq8oUtZr69fbixqEblwIzZN/Mvq+7x52/nPVeg3jy0jHkMEvlMfPkiA+KXrMv2qsuCxyaP0+N+XX2hgUmDhk05JQec6M2r0gSd+MVZZW6VOxd0PmMWp06GRZG0I6FLFK8aS3LHRbkzqcvLAk4EIcGzoyYycYhZzN1Tkf9EMLkbnv4yQM0Icm5qQucr+LuSi2TUgV9VCcV0+0t/UVzz+VopK5gA6uH82/KFuXnzthJX5HLJqLuU7Dj+sNLIOVn78eIQJDlaZGEgmLefNtNZnJM8ZR4iBqnW9Ib2+7cd0DVM54Sq8zyRfY882szKTfGPJmF7QOINYBCx9TK1LPbvMBy6yj7OVip7JPGxOFZ2jH/YGzy3G8j9Z/tW1ahJZ2DoQsWaVb3OsUXr5vpQwN4eZM4wYraNXMtuuto3k7lXEn/2Fs43pogfrg1F3maEgvYr6wk/znDKeAI5phwIs12kJIhuYe9YlNO8NzdzrUW5ujqrZCfoF5M4/g="
    - secure: "ITWhmijX0SKZX9BePvv2M+EG/wlSYdvU4pC02mDGNaQnnoi/KhXcodcelgWPPZfU7rmTYmn9HoG7thZeiVJYsrmw8rvXTlqd5Aa1mMq0QwxtduTHCVhu541RdYF/R7fTRM07a6BGaCg1FFxZy+NmVWTGbaC581FyUtjyFnCfhU/LV8EtYZRnXeXbb7z5YItr2dcm27uPjhyR1m0E7gshE0oTnbEc0jb4RZ21vIC5NOfexjEsuK+l2bOX5VzslE1Flu1saQQXPYWi+fggP+anTvZ2finGd0X0q3b9pPL//t8FmK+WzgZVis/ZW35d01/wXCRZyqn0pRLlxZZYnxmEdLTeoyODVGhqnJ1I+50ns1ybic9UG4ZdoVsx7IANbCrGrQXjJmeQj5ojXYKjKWk1Lrds4YzO827QIn/+vkQ5OD+B6boYyYlfUPYpmgvxQnfl7CGzxYTqv3JmuNFn9+mTOiNZMuDf1goG9i4bQTZdVFBtXPNRzn4x70WL4wgRguIt8ELq2hVl23xM99xKb0geJWBSuIpK5d+/fVO0+R2QwrtdDjFYPqlDOJxT8r6/yFkrJGxgxvImTETOcXHVe358EhmwiHOnDOfA+xc3PmfLa2dy2G0WIFPgtiObCGkHRFP6myRmffZApVhUG/oFiO24i2cmVPGG6uzKYVumy2OcZhw="
